# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.t1 = QtWidgets.QTextEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(0, 0, 759, 526))
        self.t1.setStyleSheet("border-style : solid;\n"
"    border-width : 1.5px")
        self.t1.setFrameShape(QtWidgets.QFrame.Box)
        self.t1.setTabChangesFocus(False)
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QTextEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(10, 10, 741, 171))
        self.t2.setStyleSheet("border-style : solid;\n"
"    border-width : 1.5px")
        self.t2.setFrameShape(QtWidgets.QFrame.Box)
        self.t2.setTabChangesFocus(False)
        self.t2.setObjectName("t2")
        self.t3 = QtWidgets.QTextEdit(self.centralwidget)
        self.t3.setGeometry(QtCore.QRect(10, 190, 351, 31))
        self.t3.setStyleSheet("border-style : solid;\n"
"    border-width : 1.5px")
        self.t3.setFrameShape(QtWidgets.QFrame.Box)
        self.t3.setTabChangesFocus(False)
        self.t3.setObjectName("t3")
        self.t4 = QtWidgets.QTextEdit(self.centralwidget)
        self.t4.setGeometry(QtCore.QRect(10, 219, 271, 31))
        self.t4.setStyleSheet("border-style : solid;\n"
"    border-width : 1.5px")
        self.t4.setFrameShape(QtWidgets.QFrame.Box)
        self.t4.setTabChangesFocus(False)
        self.t4.setObjectName("t4")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(280, 220, 81, 31))
        self.b1.setAutoFillBackground(True)
        self.b1.setCheckable(False)
        self.b1.setFlat(True)
        self.b1.setObjectName("b1")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(10, 486, 731, 31))
        self.textEdit.setMouseTracking(True)
        self.textEdit.setTabletTracking(False)
        self.textEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit.setAcceptDrops(True)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setLineWidth(1)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setUndoRedoEnabled(True)
        self.textEdit.setAcceptRichText(True)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b1.setText(_translate("MainWindow", "저장하기"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">Title: TM-02 Khanjali | Inspired by GTA5\'s TM-02 Khanjali | Completed: Dec 10, 2024 | Contributors: Kim Kang-bin (UI Design &amp; Coding), Yoo Do-yeon, Ahn Tae-young (Modeling), Yoo Do-yeon (Idea), Ahn Tae-young (Arduino &amp; Electronics) | Copyright © 2024</span></p></body></html>"))
